# ----------- CONFIGURABLE START -----------
title:            "北京优旅---内部文档"
description:      "北京优旅|国际机票"
# url:              https://liberxue.github.io # 域名
url:              http://docs-jk.worthytrip.com # 域名
host:             docs-jk.worthytrip.com
signoff:          "worthytrip" # Your name
facebook_appid:   #liberxue
#google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 9 
paginate_path: "liberxuepage:num"
#paginate_path: "page:num"
plugins: [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     true
  - name:         技术
    url:          /tech
    external:     true
  - name:         业务
    url:          /business
    external:     true
  - name:         接口规范
    url:          /spec
    external:     true
  - name:         归档
    url:          /archives
    external:     true
  - name:         标签
    url:          /tags
    external:     true
  - name:         关于
    url:          /about
    external:     true
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
#permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
